--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	04/26/24 16:34:59 
--  Relational Database:       	IBMDEV 
--  Standards Option:          	Db2 for i 
SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","BEICHHORN" ; 
  
CREATE PROCEDURE AMAZON.GET_SPOOL ( 
	IN @JOB CHAR(28) ) 
	LANGUAGE SQL 
	SPECIFIC AMAZON.GET_SPOOL 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
  
TRUNCATE AMAZON . SPOOL ; 
  
INSERT INTO AMAZON . SPOOL 
SELECT * 
FROM TABLE ( SYSTOOLS . SPOOLED_FILE_DATA ( 
JOB_NAME => @JOB , 
SPOOLED_FILE_NAME => 'QPRTSPLF' ) ) ; 
  
END  ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE AMAZON.GET_SPOOL 
TO BEICHHORN WITH GRANT OPTION ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE AMAZON.GET_SPOOL 
TO METAL WITH GRANT OPTION ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE AMAZON.GET_SPOOL 
TO PUBLIC WITH GRANT OPTION ; 
  
