--  Generate SQL 
--  Version:                   	V7R4M0 190621 
--  Generated on:              	04/26/24 16:35:49 
--  Relational Database:       	IBMDEV 
--  Standards Option:          	Db2 for i 
SET PATH "QSYS","QSYS2","SYSPROC","SYSIBMADM","BEICHHORN" ; 
  
CREATE PROCEDURE AMAZON.GET_TRACKNOS ( 
	IN @PATH CHAR(31) ) 
	LANGUAGE SQL 
	SPECIFIC AMAZON.GET_TRACKNOS 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
  
DROP TABLE IF EXISTS AMAZON . TTTEXT ; 
DROP TABLE IF EXISTS QTEMP . TTJSON2 ; 
  
CREATE TABLE AMAZON . TTTEXT ( TRACKINGNO CHAR ( 25 ) ) RCDFMT RTEXT ; 
  
INSERT INTO AMAZON . TTTEXT 
SELECT LINE FROM TABLE ( QSYS2 . IFS_READ ( PATH_NAME => @PATH , 
END_OF_LINE => 'LF' ) ) ; 
  
END  ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE AMAZON.GET_TRACKNOS 
TO BEICHHORN WITH GRANT OPTION ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE AMAZON.GET_TRACKNOS 
TO METAL WITH GRANT OPTION ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE AMAZON.GET_TRACKNOS 
TO PUBLIC WITH GRANT OPTION ; 
  
